##modelo2=name
##finalan=vector
##mdp=raster
##delimitado=raster
##finalc=output vector
##tasaprof=output raster
##profmay=output vector
##estadistica=output vector
##orientacion=output vector
##rasterizado=output raster
##finalb=output vector
##profpock=output vector
##orientacion=output vector
##profmax=output vector
##tasaprof=output vector
##cortado=output raster
##centroides=output vector
##orientacion=output vector
outputs_GDALOGRCLIPRASTERBYMASKLAYER_1=processing.runalg('gdalogr:cliprasterbymasklayer', delimitado,finalan,None,False,False,False,5,4,75.0,6.0,1.0,False,0,False,None,cortado)
outputs_QGISZONALSTATISTICS_1=processing.runalg('qgis:zonalstatistics', outputs_GDALOGRCLIPRASTERBYMASKLAYER_1['OUTPUT'],1.0,finalan,'intern_',False,estadistica)
outputs_GDALOGRRASTERIZE_1=processing.runalg('gdalogr:rasterize', outputs_QGISZONALSTATISTICS_1['OUTPUT_LAYER'],'intern_min',1,2.0,2.0,None,False,5,None,4,75.0,6.0,1.0,False,0,None,rasterizado)
outputs_GDALOGRRASTERCALCULATOR_1=processing.runalg('gdalogr:rastercalculator', outputs_GDALOGRRASTERIZE_1['OUTPUT'],'1',outputs_GDALOGRCLIPRASTERBYMASKLAYER_1['OUTPUT'],'1',None,'1',None,'1',None,'1',None,'1','B/A',None,5,None,tasaprof)
outputs_QGISZONALSTATISTICS_2=processing.runalg('qgis:zonalstatistics', mdp,1.0,outputs_QGISZONALSTATISTICS_1['OUTPUT_LAYER'],'orig_',False,profmay)
outputs_QGISFIELDCALCULATOR_1=processing.runalg('qgis:fieldcalculator', outputs_QGISZONALSTATISTICS_2['OUTPUT_LAYER'],'prof_pock',0,10.0,3.0,True,'orig_min-intern_min',profpock)
outputs_GRASS7R.TO.VECT_1=processing.runalg('grass7:r.to.vect', outputs_GDALOGRRASTERCALCULATOR_1['OUTPUT'],1,False,None,0,tasaprof)
outputs_QGISSELECTBYATTRIBUTE_1=processing.runalg('qgis:selectbyattribute', outputs_GRASS7R.TO.VECT_1['output'],'value',0,'1')
outputs_QGISEXPORTADDGEOMETRYCOLUMNS_1=processing.runalg('qgis:exportaddgeometrycolumns', outputs_QGISFIELDCALCULATOR_1['OUTPUT_LAYER'],1,finalb)
outputs_QGISSAVESELECTEDFEATURES_1=processing.runalg('qgis:saveselectedfeatures', outputs_QGISSELECTBYATTRIBUTE_1['OUTPUT'],profmax)
outputs_QGISORIENTEDMINIMUMBOUNDINGBOX_1=processing.runalg('qgis:orientedminimumboundingbox', outputs_QGISEXPORTADDGEOMETRYCOLUMNS_1['OUTPUT'],True,orientacion)
outputs_QGISFIELDCALCULATOR_2=processing.runalg('qgis:fieldcalculator', outputs_QGISORIENTEDMINIMUMBOUNDINGBOX_1['OUTPUT'],'angulos',0,10.0,3.0,True,'CASE \nWHEN "HEIGHT" <  "WIDTH" AND "ANGLE" < 0 THEN 90 +abs(  "ANGLE" ) \nWHEN "HEIGHT" <  "WIDTH" AND "ANGLE" > 0 THEN 270 - "ANGLE" \nWHEN "HEIGHT" >  "WIDTH" AND "ANGLE" < 0 THEN abs("ANGLE")\nWHEN "HEIGHT" >  "WIDTH" AND "ANGLE" > 0 THEN "ANGLE"\nEND',orientacion)
outputs_QGISPOLYGONCENTROIDS_1=processing.runalg('qgis:polygoncentroids', outputs_QGISFIELDCALCULATOR_2['OUTPUT_LAYER'],orientacion)
outputs_SAGAADDPOINTATTRIBUTESTOPOLYGONS_1=processing.runalg('saga:addpointattributestopolygons', outputs_QGISEXPORTADDGEOMETRYCOLUMNS_1['OUTPUT'],outputs_QGISPOLYGONCENTROIDS_1['OUTPUT_LAYER'],'angulos',False,finalc)
outputs_QGISPOLYGONCENTROIDS_2=processing.runalg('qgis:polygoncentroids', outputs_SAGAADDPOINTATTRIBUTESTOPOLYGONS_1['OUTPUT'],centroides)